# -- coding: utf-8 --

# Form implementation generated from reading ui file 'ilkSayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import kullaniciAnaSayfa
import kullanicilar as Kullanici

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        
        #setExtendedState(JFrame.MAXIMIZED_BOTH);
        MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(996, 672)
        #MainWindow.fixedsize(1920, 1080)
        MainWindow.setFixedSize(1920, 1080)
        #MainWindow.adjustSize()
        MainWindow.setStyleSheet("background-color: rgb(47, 91, 76);\n"
"background-color: rgb(47, 91, 76);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(34, 136, 85);\n"
"background-color: rgb(47, 91, 76);")
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 20, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("""
            QPushButton {
                background-color: rgb(131, 65, 0);
                border-radius: 10px;  /* Yuvarlaklık */
                padding: 10px;
            }
            QPushButton:hover {
                background-color: rgb(170, 70, 0);
            }
            QPushButton:pressed {
                background-color: rgb(145, 70, 0);
            }
        """)

        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(325, 20, 1300, 250))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(55)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"background-image: url(:/gardenPic/ustYazi.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1300, 815, 261, 131))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"                background-color: rgb(131, 65, 0);\n"
"                border-radius: 10px;  /* Yuvarlaklık */\n"
"                padding: 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(170, 70, 0);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: rgb(145, 70, 0);\n"
"            }")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(500, 300, 721, 81))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"                background-color: rgb(131, 65, 0);\n"
"                border-radius: 10px;  /* Yuvarlaklık */\n"
"                padding: 10px;\n"
"           ")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(500, 400, 721, 550))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_23 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_23.setObjectName("pushButton_23")
        self.gridLayout_3.addWidget(self.pushButton_23, 1, 2, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout_3.addWidget(self.pushButton_31, 3, 0, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout_3.addWidget(self.pushButton_32, 3, 1, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_24.setObjectName("pushButton_24")
        self.gridLayout_3.addWidget(self.pushButton_24, 1, 3, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_25.setObjectName("pushButton_25")
        self.gridLayout_3.addWidget(self.pushButton_25, 1, 1, 1, 1)
        self.pushButton_26 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_26.setObjectName("pushButton_26")
        self.gridLayout_3.addWidget(self.pushButton_26, 1, 0, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout_3.addWidget(self.pushButton_27, 0, 0, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout_3.addWidget(self.pushButton_28, 0, 1, 1, 1)
        self.pushButton_29 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout_3.addWidget(self.pushButton_29, 0, 2, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout_3.addWidget(self.pushButton_30, 0, 3, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout_3.addWidget(self.pushButton_34, 3, 3, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout_3.addWidget(self.pushButton_36, 4, 1, 1, 1)
        self.pushButton_35 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout_3.addWidget(self.pushButton_35, 4, 0, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout_3.addWidget(self.pushButton_37, 4, 2, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout_3.addWidget(self.pushButton_38, 4, 3, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(30)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setStyleSheet("background-color: rgb(170, 160, 140);\n"
"font: \"Maiandra GD\";")
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout_3.addWidget(self.pushButton_33, 3, 2, 1, 1)

        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(325, 20, 1300, 250))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(55)
        self.label2.setFont(font)
        self.label2.setStyleSheet("\n"
"background-image: url(:/gardenPic/ustYazi.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"")
        self.label2.setAlignment(QtCore.Qt.AlignCenter)
        self.label2.setObjectName("titleLabel")



        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(1550, -90, 487, 500))
        self.graphicsView.setStyleSheet("border-color: rgb(47, 91, 76);\n"
"border-left-color: rgb(47, 91, 76);\n"
"background: transparent;\n"
"\n"
"background-image:  url(:/gardenPic/saksı-Photoroom.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"")
        self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(-70, 600, 487, 500))
        self.graphicsView_2.setStyleSheet("border-color: rgb(47, 91, 76);\n"
"border-left-color: rgb(47, 91, 76);\n"
"background: transparent;\n"
"\n"
"background-image: url(:/gardenPic/saksı-Photoroom2.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"")
        self.graphicsView_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView_2.setObjectName("graphicsView_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Bahçe Kirala"))
        self.label.setText(_translate("MainWindow", "Bahçeler"))
        self.label2.setText(_translate("MainWindow", "GARDEN HUB"))
        self.pushButton_2.setText(_translate("MainWindow", "<- Geri"))
        self.pushButton_23.setText(_translate("MainWindow", "\n"
"7\n"
""))
        self.pushButton_31.setText(_translate("MainWindow", "\n"
"9\n"
""))
        self.pushButton_32.setText(_translate("MainWindow", "\n"
"10\n"
""))
        self.pushButton_24.setText(_translate("MainWindow", "\n"
"8\n"
""))
        self.pushButton_25.setText(_translate("MainWindow", "\n"
"6\n"
""))
        self.pushButton_26.setText(_translate("MainWindow", "\n"
"5\n"
""))
        self.pushButton_27.setText(_translate("MainWindow", "\n"
"1\n"
""))
        self.pushButton_28.setText(_translate("MainWindow", "\n"
"2\n"
""))
        self.pushButton_29.setText(_translate("MainWindow", "\n"
"3\n"
""))
        self.pushButton_30.setText(_translate("MainWindow", "\n"
"4\n"
""))
        self.pushButton_34.setText(_translate("MainWindow", "\n"
"12\n"
""))
        self.pushButton_36.setText(_translate("MainWindow", "\n"
"14\n"
""))
        self.pushButton_35.setText(_translate("MainWindow", "\n"
"13\n"
""))
        self.pushButton_37.setText(_translate("MainWindow", "\n"
"15\n"
""))
        self.pushButton_38.setText(_translate("MainWindow", "\n"
"16\n"
""))
        self.pushButton_33.setText(_translate("MainWindow", "\n"
"11\n"
""))
import resimler_rc


class Bahceler(QtWidgets.QMainWindow):
    def __init__(self, kullanici: Kullanici.Kullanici) -> None:
            super().__init__()
            self.ui = Ui_MainWindow()  # Burada doğru bir şekilde ui nesnesi başlatılıyor.
            self.ui.setupUi(self)
            self.ui.pushButton_2.clicked.connect(self.geriGit)
    
    def geriGit(self,kullanici):
        self.close()
        self.ilkSayfa = kullaniciAnaSayfa.KullaniciAnaSayfa(kullanici)
        self.ilkSayfa.show()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = Bahceler()
    window.show()
    sys.exit(app.exec_())