# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ilkSayfa.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class KullaniciAnaSayfa(QtWidgets.QMainWindow):
    def __init__(self, kullanici: Kullanici.Kullanici) -> None:
        super().__init__()
        self.ui = Ui_MainWindow()  # Burada doğru bir şekilde ui nesnesi başlatılıyor.
        self.ui.setupUi(self)
        self.kullanici = kullanici

        # Butonlara işlev ekleme
        self.ui.pushButton_3.clicked.connect(self.ekipmanlaraGit)
        self.ui.pushButton_4.clicked.connect(self.bahcelereGit)
        self.ui.pushButton_2.clicked.connect(self.bakiyeGoruntule)

    def ekipmanlaraGit(self):
        self.close()
        self.ilkSayfa = ekipmanlar.Ekipman()
        self.ilkSayfa.show()

    def bahcelereGit(self):
        self.close()
        self.ilkSayfa = bahceler.Bahceler()
        self.ilkSayfa.show()

    def bakiyeGoruntule(self):
        # Kullanıcı bakiyesini mesaj kutusunda göster
        bakiye_mesaji = f"Bakiyeniz: {self.kullanici.butce} TL"
        QMessageBox.information(self, "Bakiye Görüntüle", bakiye_mesaji)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)

    # Örnek bir kullanıcı nesnesi oluştur
    ornek_kullanici = Kullanici(
        isim="Ali",
        soyisim="Veli",
        kullanici_id=1,
        mail="ali@veli.com",
        sifre="1234",
        bdate="1990-01-01",
        butce=500,
        user_type="standart"
    )

    window = KullaniciAnaSayfa(ornek_kullanici)
    window.show()
    sys.exit(app.exec_())

import bahceler
import ekipmanlar
import kullanicilar as Kullanici

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        
        #setExtendedState(JFrame.MAXIMIZED_BOTH);
        MainWindow.setObjectName("MainWindow")
        #MainWindow.resize(996, 672)
        #MainWindow.fixedsize(1920, 1080)
        MainWindow.setFixedSize(1920, 1080)
        #MainWindow.adjustSize()
        MainWindow.setStyleSheet("background-color: rgb(47, 91, 76);\n"
"background-color: rgb(47, 91, 76);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(34, 136, 85);\n"
"background-color: rgb(47, 91, 76);")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(600, 400, 731, 334))
        self.widget.setObjectName("widget")
       
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(325, 125, 1300, 250))
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(55)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"background-image: url(:/gardenPic/ustYazi.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(1550, -90, 487, 500))
        self.graphicsView.setStyleSheet("border-color: rgb(47, 91, 76);\n"
"border-left-color: rgb(47, 91, 76);\n"
"background: transparent;\n"
"\n"
"background-image:  url(:/gardenPic/saksı-Photoroom.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"")
        
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("\n"
"            QPushButton {\n"
"                background-color: rgb(191, 183, 165);\n"
"                border-radius: 20px;  /* Yuvarlaklık */\n"
"                padding: 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(210, 200, 180);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: rgb(170, 160, 140);\n"
"            }")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"            QPushButton {\n"
"                background-color: rgb(191, 183, 165);\n"
"                border-radius: 20px;  /* Yuvarlaklık */\n"
"                padding: 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(210, 200, 180);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: rgb(170, 160, 140);\n"
"            }\n"
"        ")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("\n"
"            QPushButton {\n"
"                background-color: rgb(191, 183, 165);\n"
"                border-radius: 20px;  /* Yuvarlaklık */\n"
"                padding: 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(210, 200, 180);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: rgb(170, 160, 140);\n"
"            }")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)###############3
        

        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Maiandra GD")
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("\n"
"            QPushButton {\n"
"                background-color: rgb(191, 183, 165);\n"
"                border-radius: 20px;  /* Yuvarlaklık */\n"
"                padding: 10px;\n"
"            }\n"
"            QPushButton:hover {\n"
"                background-color: rgb(210, 200, 180);\n"
"            }\n"
"            QPushButton:pressed {\n"
"                background-color: rgb(170, 160, 140);\n"
"            }")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 1, 1, 1)
        self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_2.setGeometry(QtCore.QRect(-70, 600, 487, 500))
        self.graphicsView_2.setStyleSheet("border-color: rgb(47, 91, 76);\n"
"border-left-color: rgb(47, 91, 76);\n"
"background: transparent;\n"
"\n"
"background-image: url(:/gardenPic/saksı-Photoroom2.png);\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"")
        self.graphicsView_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView_2.setObjectName("graphicsView_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "\n"
"PAZARA\n"
"ÜRÜN EKLE\n"
""))
        self.pushButton_2.setText(_translate("MainWindow", "\n"
"BAKİYE\n"
"GÖRÜNTÜLE\n"
""))

        self.pushButton_3.setText(_translate("MainWindow", "\n"
"EKİPMANLARIN\n"
"DURUMUNU GÖR\n"
""))
        self.pushButton_4.setText(_translate("MainWindow", "\n"
"BAHÇELERİ\n"
"GÖRÜNTÜLE\n"
""))
        self.label.setText(_translate("MainWindow", "GARDEN HUB"))
import resimler_rc


class KullaniciAnaSayfa(QtWidgets.QMainWindow):
        def __init__(self,kullanici: Kullanici.Kullanici) -> None:
                super().__init__()
                self.ui = Ui_MainWindow()  # Burada doğru bir şekilde ui nesnesi başlatılıyor.
                self.ui.setupUi(self)
                self.kullanici=kullanici
                self.ui.pushButton_3.clicked.connect(self.ekipmanlaraGit)
                self.ui.pushButton_4.clicked.connect(self.bahcelereGit)
                self.ui.pushButton_2.clicked.connect(self.bakiyeGoruntule)
                
        def ekipmanlaraGit(self):
            self.close()
            self.ilkSayfa = ekipmanlar.Ekipman()
            self.ilkSayfa.show()
        def bahcelereGit(self):
            self.close()
            self.ilkSayfa = bahceler.Bahceler()
            self.ilkSayfa.show()   
        def bakiyeGoruntule(self):
                bakiye_mesaji = f"Bakiyeniz: {self.kullanici.butce} TL"
                QMessageBox.information(self, "Bakiye Görüntüle", bakiye_mesaji)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = KullaniciAnaSayfa()
    window.show()
    sys.exit(app.exec_())
    